###### model name ######
model_name: 'v1_weighted_answerembed_1hidden_dropout'

###### model architecture-related settings ######
num_hidden_layers: 1
hidden_size: 1536
use_answer_embeddings: true
use_answer_embedding_z_normalization: true
use_dropout: true
dropout_input_probability: 0.2
dropout_hidden_probability: 0.5
use_batch_normalization: false

###### training-related hyperparameters ######
batch_size: 5000
learning_rate: 1.e-4
shuffle: true

###### loss-function parameters ######
use_class_weights: true

###### epoch-related settings ######

# max_epochs: Training will cut off here if it hasn't already cut-off from another condition.
max_epochs: 200

# snapshot_every_epochs: How frequently to take a snapshot.  This will be the
# restore point if our run is interrupted, for example by spot instance eviction.
snapshot_every_epochs: 50

# metrics_every_epochs: How frequently to calculate performance metrics for both
# the training and validation set.  This will determine the resolution of
# graphs.  Tracking performance adds an overhead on training and requires doing
# an inference run over the validation set.
metrics_every_epochs: 1
